[project]
name = "app"
version = "0.1.0"
description = "Streamlit frontend"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "pillow>=11.2.1",
    "requests>=2.32.3",
    "streamlit>=1.45.1",
    "streamlit-drawable-canvas>=0.9.3",
]
