services:
  backend:
    build: ./backend
    container_name: backend
    # expose the backend to linked services in same docker network, but not to host machine
    expose:
      - ${BACKEND_PORT}
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
    # we have a chain of dependencies i.e. db < backend < frontend < caddy (where < == 'depends on')
    depends_on:
      db:
        condition: service_healthy
    networks: [mnist-net]

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - ${FRONTEND_PORT}
    depends_on: [backend]
    networks: [mnist-net]

  db:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    # we do expose the db to the host so we can connect to it and query the data (e.g via pgAdmin)
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks: [mnist-net]

  caddy:
    image: caddy:2.10.0-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data  # certs + keys
      - caddy_config:/config  # autosaved JSON config
    depends_on: [frontend]
    networks: [mnist-net]

networks:
  mnist-net:
    driver: bridge

volumes:
  caddy_config:
  caddy_data:
  pgdata:
